//! Windows shell: WinUI 3 (Windows App SDK) + WebView2. Compiles to nothing on other targets.
//!
//! | module            | owns                                                                |
//! |-------------------|---------------------------------------------------------------------|
//! | `cli`, `config`   | command line and the resolved run configuration                     |
//! | `platform`        | COM, DPI awareness, Windows App Runtime dependency, message boxes   |
//! | `app`             | the XAML `Application` subclass and the exit code                   |
//! | `exec`            | a single-threaded executor on the UI `DispatcherQueue`              |
//! | `engine`          | the shared `CoreWebView2Environment` and engine-side extension calls|
//! | `browser`         | app-wide controller; the points where vsesvit-core plugs in         |
//! | `window`          | one window: tab strip in the title bar, toolbar, bars, page grid    |
//! | `tab`             | one tab: `TabViewItem` header, `WebView2`, navigation state         |
//! | `bookmarks_bar`   | bookmarks bar buttons and folder menus                              |
//! | `popup`           | extension action buttons and their popup flyout                     |
//! | `dialogs`         | Bookmarks / History / Extensions / Settings / About                 |
//! | `shortcuts`       | keyboard bindings, shared by XAML accelerators and the page script  |
//! | `omnibox`         | provisional address-box input handling                              |
//! | `capture`         | PNG capture of web content and of the whole window, without focus   |
//! | `automation`      | scripted UI runs (`--ui-smoke`) built on `capture`                  |
//! | `updates`         | the self-update state machine, its schedule, the update commands    |
//! | `bindings`        | generated; regenerate with `tools/bindgen` (see `bindings.txt`)     |
#![cfg(windows)]

mod app;
mod automation;
#[rustfmt::skip]
#[allow(
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    dead_code,
    clippy::all,
    clippy::pedantic,
    reason = "generated by tools/bindgen"
)]
mod bindings;
mod bookmarks_bar;
mod browser;
mod capture;
mod cli;
mod config;
mod dialogs;
mod engine;
mod exec;
mod logging;
mod omnibox;
mod platform;
mod popup;
mod shortcuts;
mod tab;
mod updates;
mod window;
mod xaml;

use std::process::ExitCode;

use config::{Config, Mode};

pub fn run() -> ExitCode {
    let args = match cli::parse(std::env::args_os().skip(1)) {
        Ok(cli::Parsed::Run(args)) => args,
        Ok(cli::Parsed::Help) => {
            platform::attach_parent_console();
            println!("{}", cli::USAGE);
            return ExitCode::SUCCESS;
        }
        Ok(cli::Parsed::Version) => {
            platform::attach_parent_console();
            println!("vsesvit {}", env!("CARGO_PKG_VERSION"));
            return ExitCode::SUCCESS;
        }
        Ok(cli::Parsed::Update(command)) => {
            platform::attach_parent_console();
            return updates::run_command(command);
        }
        Err(e) => {
            platform::attach_parent_console();
            eprintln!("vsesvit: {e}\n\n{}", cli::USAGE);
            return ExitCode::from(2);
        }
    };
    let config = match Config::resolve(args) {
        Ok(config) => config,
        Err(e) => {
            eprintln!("vsesvit: {e}");
            return ExitCode::FAILURE;
        }
    };
    logging::init(&config.profile_dir);
    log::info!(
        "vsesvit {} starting, profile {}",
        env!("CARGO_PKG_VERSION"),
        config.profile_dir.display()
    );

    if let Mode::SelfTest { out_dir } = &config.mode {
        log::error!(
            "--self-test {}: the end-to-end checks are not part of this build yet",
            out_dir.display()
        );
        return ExitCode::FAILURE;
    }

    let interactive = config.mode.is_interactive();
    if let Err(e) = platform::init() {
        log::error!("{e}");
        if interactive {
            platform::report_startup_failure(&e);
        }
        return ExitCode::FAILURE;
    }
    app::run(config)
}
