//! `vsesvit-<v>-1-x86_64.pkg.tar.zst`, assembled the way makepkg does it: `.PKGINFO`, an
//! `.MTREE` from `bsdtar --format=mtree`, then a zstd tar under fakeroot with the metadata
//! files first.

use std::path::Path;
use std::process::Command;

use crate::Result;
use crate::ctx::{BINARY, Ctx, HOMEPAGE, LICENSE, MAINTAINER, SUMMARY};

use super::deps;
use super::stage::Stage;
use super::util;

/// makepkg's mtree options (`create_package` in makepkg).
const MTREE_OPTIONS: &str = "!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link";

pub fn build(ctx: &Ctx, stage: &Stage, artifact: &Path) -> Result {
    let root = &stage.root;
    let builddate = std::env::var("SOURCE_DATE_EPOCH").ok().and_then(|s| s.parse::<u64>().ok()).unwrap_or_else(|| {
        std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).map(|d| d.as_secs()).unwrap_or(0)
    });
    let mut pkginfo = format!(
        "# Generated by cargo xtask package pacman\n\
         pkgname = {BINARY}\n\
         pkgbase = {BINARY}\n\
         xdata = pkgtype=pkg\n\
         pkgver = {version}-1\n\
         pkgdesc = {SUMMARY}\n\
         url = {HOMEPAGE}\n\
         builddate = {builddate}\n\
         packager = {MAINTAINER}\n\
         size = {size}\n\
         arch = x86_64\n\
         license = {LICENSE}\n",
        version = ctx.version,
        size = util::tree_size(root)?,
    );
    for dep in deps::required(|d| d.pacman) {
        pkginfo.push_str(&format!("depend = {dep}\n"));
    }
    for dep in deps::optional(|d| d.pacman) {
        pkginfo.push_str(&format!("optdepend = {dep}: {}\n", deps::OPTIONAL_REASON));
    }
    util::write(&root.join(".PKGINFO"), pkginfo)?;

    let files = files_list(root, &[".PKGINFO"])?;
    util::pipe(
        bsdtar(root)
            .args(["--format=mtree", "--options", MTREE_OPTIONS, "--exclude", ".MTREE", "--null", "--files-from"])
            .arg(&files),
        Command::new("gzip").args(["-c", "-f", "-n"]),
        &root.join(".MTREE"),
    )?;

    let files = files_list(root, &[".MTREE", ".PKGINFO"])?;
    util::pipe(
        bsdtar(root).args(["--no-fflags", "--null", "--files-from"]).arg(&files),
        Command::new("zstd").args(["-c", "-T0", "--ultra", "-20", "-"]),
        artifact,
    )
}

/// `fakeroot bsdtar -cnf -` in `root`: everything appears root-owned, and `-n` archives exactly
/// the listed paths, so the list order is the archive order.
fn bsdtar(root: &Path) -> Command {
    let mut cmd = Command::new("fakeroot");
    cmd.args(["bsdtar", "-cnf", "-"]).env("LANG", "C").current_dir(root);
    cmd
}

/// NUL-separated list of `first` then every path under `root` except the metadata files, so
/// pacman reads `.PKGINFO` before anything else.
fn files_list(root: &Path, first: &[&str]) -> Result<std::path::PathBuf> {
    let mut list = Vec::new();
    for name in first {
        list.extend_from_slice(name.as_bytes());
        list.push(0);
    }
    for rel in util::walk(root)? {
        let rel = rel.to_string_lossy();
        if rel.starts_with('.') {
            continue;
        }
        list.extend_from_slice(rel.as_bytes());
        list.push(0);
    }
    let path = root.parent().ok_or("stage root has no parent")?.join("files.list");
    util::write(&path, list)?;
    Ok(path)
}
